steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'optimum-rock-404123']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/users-app-server:$COMMIT_SHA', '-f', 'client/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/users-app-server:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-client 
    --image=europe-west1-docker.pkg.dev/$PROJECT_ID/users-app-server:$COMMIT_SHA
    --region=europe-west1 
    --platform=managed 
    --allow-unauthenticated 
    --port=5173"
  ]

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/users-app-server:$COMMIT_SHA'
